{   'application': False,
    'assets': {},
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'data': [   'security/groups.xml',
                'security/ir.model.access.csv',
                'views/assets.xml',
                'views/group_form.xml',
                'views/group_tree.xml',
                'views/member_tree.xml',
                'views/site_form.xml',
                'views/site_tree.xml',
                'views/vpn_portal_templates.xml',
                'views/menu.xml',
                ],
    'demo': [],
    'depends': ['base', 'portal'],
    'external_dependencies': {'bin': [], 'python': ['jingtrang']},
    'name': 'ovpn_manager',
    'test': [],
    'version': '16.0.1.0'}
