{   'application': False,
    'assets': {},
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'data': [   'security/groups.xml',
                'views/assets.xml',
                'views/group_form.xml',
                'views/group_tree.xml',
                'views/member_tree.xml',
                'views/site_form.xml',
                'views/site_tree.xml',
                'views/menu.xml',
                'security/ir.model.access.csv'],
    'demo': [],
    'depends': ['base'],
    'external_dependencies': {'bin': [], 'python': []},
    'name': 'ovpn_manager',
    'test': [],
    'version': '16.0.1.0'}
